<Project>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Terminal.Core' or '$(MSBuildProjectName)' == 'Terminal.Controls'">
    <Version Condition="'$(Version)' == ''">0.1.0</Version>
    <Authors>shigekazukoya</Authors>
    <Company>shigekazukoya</Company>
    <RepositoryUrl>https://github.com/shigekazukoya/Terminal</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Terminal.Core' or '$(MSBuildProjectName)' == 'Terminal.Controls'">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

</Project>
