param(
    [string]$Version = "17.0.0",
    [string]$OutputPath = "$PSScriptRoot/../src/Terminal.Core/Unicode/UnicodeWidthData.g.cs"
)

$ErrorActionPreference = "Stop"
$url = "https://www.unicode.org/Public/$Version/ucd/EastAsianWidth.txt"
$temporaryFile = [System.IO.Path]::GetTempFileName()
$emojiUrl = "https://www.unicode.org/Public/$Version/ucd/emoji/emoji-data.txt"
$emojiTemporaryFile = [System.IO.Path]::GetTempFileName()
try {
    Invoke-WebRequest -Uri $url -OutFile $temporaryFile
    Invoke-WebRequest -Uri $emojiUrl -OutFile $emojiTemporaryFile
    $groups = @{
        Wide = [System.Collections.Generic.List[object]]::new()
        Ambiguous = [System.Collections.Generic.List[object]]::new()
        EmojiPresentation = [System.Collections.Generic.List[object]]::new()
    }
    foreach ($line in Get-Content -LiteralPath $temporaryFile) {
        if ($line -notmatch '^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(W|F|A)\b') { continue }
        $start = [Convert]::ToInt32($Matches[1], 16)
        $end = if ($Matches[2]) { [Convert]::ToInt32($Matches[2], 16) } else { $start }
        $key = if ($Matches[3] -eq 'A') { 'Ambiguous' } else { 'Wide' }
        $groups[$key].Add(@($start, $end))
    }
    foreach ($line in Get-Content -LiteralPath $emojiTemporaryFile) {
        if ($line -notmatch '^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*Emoji_Presentation\b') { continue }
        $start = [Convert]::ToInt32($Matches[1], 16)
        $end = if ($Matches[2]) { [Convert]::ToInt32($Matches[2], 16) } else { $start }
        $groups.EmojiPresentation.Add(@($start, $end))
    }

    $builder = [System.Text.StringBuilder]::new()
    [void]$builder.AppendLine('// <auto-generated />')
    [void]$builder.AppendLine("// Generated from Unicode $Version EastAsianWidth.txt: $url")
    [void]$builder.AppendLine('namespace Terminal.Unicode;')
    [void]$builder.AppendLine('internal static class UnicodeWidthData')
    [void]$builder.AppendLine('{')
    [void]$builder.AppendLine("    internal const string UnicodeVersion = `"$Version`";")
    foreach ($key in @('Wide', 'Ambiguous', 'EmojiPresentation')) {
        [void]$builder.AppendLine("    private static readonly int[] ${key}Ranges =")
        [void]$builder.AppendLine('    [')
        foreach ($range in $groups[$key]) {
            [void]$builder.AppendLine(('        0x{0:X}, 0x{1:X},' -f $range[0], $range[1]))
        }
        [void]$builder.AppendLine('    ];')
    }
    [void]$builder.AppendLine('    internal static bool IsWide(int value) => Contains(WideRanges, value);')
    [void]$builder.AppendLine('    internal static bool IsAmbiguous(int value) => Contains(AmbiguousRanges, value);')
    [void]$builder.AppendLine('    internal static bool IsEmojiPresentation(int value) => Contains(EmojiPresentationRanges, value);')
    [void]$builder.AppendLine('    private static bool Contains(int[] ranges, int value)')
    [void]$builder.AppendLine('    {')
    [void]$builder.AppendLine('        int low = 0, high = ranges.Length / 2 - 1;')
    [void]$builder.AppendLine('        while (low <= high)')
    [void]$builder.AppendLine('        {')
    [void]$builder.AppendLine('            int middle = low + ((high - low) / 2), offset = middle * 2;')
    [void]$builder.AppendLine('            if (value < ranges[offset]) high = middle - 1;')
    [void]$builder.AppendLine('            else if (value > ranges[offset + 1]) low = middle + 1;')
    [void]$builder.AppendLine('            else return true;')
    [void]$builder.AppendLine('        }')
    [void]$builder.AppendLine('        return false;')
    [void]$builder.AppendLine('    }')
    [void]$builder.AppendLine('}')
    [System.IO.File]::WriteAllText([System.IO.Path]::GetFullPath($OutputPath), $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
}
finally {
    Remove-Item -LiteralPath $temporaryFile -Force -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $emojiTemporaryFile -Force -ErrorAction SilentlyContinue
}
